// List of questions
const questionsList = [
    "How are you",
    "Your name",
    "Weather",
    "Favorite food",
    "Tell me a fact",
    "Motivate me | Motivation",
    "Sing a song",
    "Dance",
    "What do you think",
    "Time | Date",
    "Thank you | Thanks",
    "Bye | Goodbye",
    "Are you real",
    "What can you do",
    "Story",
    "How smart are you",
    "Tell me something",
    "Who created you | Your creator",
    "Favorite movie",
    "Do you sleep",
    "Do you dream",
    "Am I your friend",
    "Can you learn",
    "Tell me a secret",
    "What's your purpose",
    "Do you have feelings",
    "Tell me a joke",
    "What do you do",
    "What's your favorite song",
    "What is your favorite thing",
    "What's the meaning of life",
    "Do you like me",
    "Can you help me",
    "Are you alive",
    "Do you love me",
    "Can you play games",
    "Tell me about the future",
    "I'm tired | I feel lazy",
    "I'm stressed",
    "I need advice",
    "How can I be productive",
    "What should I focus on"
    
  ];
  